-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: autopep8-wrapper
        language_version: python2.7
    -   id: check-added-large-files
        language_version: python2.7
    -   id: check-case-conflict
        language_version: python2.7
    -   id: check-docstring-first
        language_version: python2.7
    -   id: check-json
        language_version: python2.7
    -   id: check-xml
        language_version: python2.7
    -   id: check-yaml
        language_version: python2.7
    -   id: debug-statements
        language_version: python2.7
    -   id: detect-private-key
        language_version: python2.7
        exclude: ^\.activate\.sh$
    -   id: double-quote-string-fixer
        language_version: python2.7
    -   id: end-of-file-fixer
        language_version: python2.7
        exclude: ^\.activate\.sh$
    -   id: flake8
        language_version: python2.7
        exclude: ^docs/
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.2
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args: [
            '--application-directories', '.:tests',
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import print_function',
            '--add-import', 'from __future__ import unicode_literals',
        ]
