repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
        exclude: ^docs/
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            --add-import, 'from __future__ import absolute_import',
            --add-import, 'from __future__ import print_function',
            --add-import, 'from __future__ import unicode_literals',
            --application-directories, '.:tests',
        ]
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
