-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
        exclude: ^\.activate\.sh$
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        exclude: ^\.activate\.sh$
    -   id: flake8
        exclude: ^docs/
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import print_function
        - --add-import
        - from __future__ import unicode_literals
        - --application-directories
        - .:tests
-   repo: local
    hooks:
    -   id: pylint
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
