language: python
dist: trusty
env:
    # putting this ahead of the `python` directive
    #   means we start all lints before any tests
    - TOXENV=lint
    - TOXENV=python
python:
    - pypy

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true

install: ./venv_update.py venv= $VIRTUAL_ENV install= -r CI/requirements.txt
script:
    - . CI/env
    - tox


# sudo:false gives us the new, faster cluster and enables caches for public repos
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
