language: python
dist: trusty

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true
    # In order of most-valuable tests first
    include:
        - env: TOXENV=lint
          python: 3.6
        - env: TOXENV=lint
          python: 2.7

        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=py26
          python: 2.6
        - env: TOXENV=pypy
          python: pypy-5.4.1
        - env: TOXENV=py27
          python: 2.7
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=latest-pip
          python: 3.6

install: ./venv_update.py venv= $VIRTUAL_ENV install= -r CI/requirements.txt
script: tox

cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
