language: python
env:
    # putting env: ahead of python: means we start all lints before any tests
    - JOB=lint
    - JOB=test
python:
    # in order of most-valuable tests first
    - "3.5"
    - "2.6"
    - pypy
    - "2.7"
    - "3.4"

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true
    # really only need to run lint twice
    exclude:
        - python: "2.6"
          env: JOB=lint
        - python: pypy
          env: JOB=lint
        - python: '3.4'
          env: JOB=lint

before_install: export PY=$TRAVIS_PYTHON_VERSION
install: ./CI/install
script: ./CI/main $PY $JOB


# sudo:false gives us the new, faster cluster and enables caches for public repos
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
